GET http://localhost:8080/api/books

###

GET http://localhost:8080/api/books/1

###

GET http://localhost:8080/api/books/2

###

GET http://localhost:8080/api/books/3

###

GET http://localhost:8080/api/books/951

###

GET http://localhost:8080/api/books/isbn/1234567890

###

GET http://localhost:8080/api/books/isbn/9781617294945

###

GET http://localhost:8080/api/books/isbn/87765

### Add a new book
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Spring in Action",
  "isbn": "9781617294945",
  "price": 123,
  "publicationDate": "2024-09-01"
}

### Delete a book (replace {bookId} with the actual ID)
DELETE http://localhost:8080/api/books/951

### Update a book (replace {bookId} with the actual ID)
PUT http://localhost:8080/api/books/951
Content-Type: application/json

{
  "title": "Spring Boot in Action",
  "isbn": "9781617294945",
  "price": 124,
  "publicationDate": "2024-09-02"
}

